config/routes.rb
Rails.application.routes.draw do

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  devise_for :users
  root to: 'pages#home'

  # # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html




  # devise_for :users, path: 'users', controllers: {
  #   sessions: "users/sessions"
  # }
  get "/businesses/helped", to: "businesses#order_history_businesses", as: "businesses_helped"
  get "/about", to: "pages#about", as: "about"

  resources :businesses, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :business_offers, shallow: true
  end

  resources :orders, only: [:index, :new, :create, :edit, :update, :destroy] do
    resources :order_items, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :payments, only: [:new]
  end



  post "/businesses/:business_id/business_offers/:id/add", to: "business_offers#add_to_bag", as: "add_offer_to_bag"
  post "/businesses/:business_id/business_offers/:id/remove", to: "business_offers#remove_from_bag", as: "remove_from_bag"
  post "/businesses/:business_id/business_offers/:id/increase", to: "business_offers#increase_to_bag", as: "increase_offer_to_bag"
  get "/orders/:business_id/increase", to: "orders#update_total_amount_cents", as: "update_total_amount_cents"
  get "/orders/:business_id/decrease", to: "orders#update_total_amount_cents_checkout", as: "update_total_amount_cents_checkout"
  get "/orders/cart", to: "orders#show_cart", as: "show_cart"



  # get "/businesses/:user_id/withdraw", to: "businesses#withdraw", as: "withdraw"
  # get "/orders/:user_id/transactions", to: "orders#view_history", as: "view_user_history"
  # get "/orders/:user_id/view_all", to: "orders#view_all", as: "view_user_orders"


end

app/views/shared/_banner.html.erb
<div class="b-main-container">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.2)), url(<%= asset_path('banner.jpg') %>);">
    <div class="">
      <h2 style="text-shadow: 1px 1px 6px black; text-align: left">Help your favorite places to survive the COVID-19 crisis. <br>Get discounted credits to use in future.</h2>
      <br>
      <br>
      <a class="button-blue" href="/businesses">Discover Places</a>
    </div>
      <div class="scroll1">
        <img src="<%= asset_path('scroll.svg')%>" alt="" onclick="topFunction1()" id="myArrow1">
      </div>

  </div>


  <div class="banner-2">
    <div class="sec2">
      <h2>

          Hit two birds with one stone!! <br>
          Support your community and save money.
          <br><br>
          Browse in to your favorite local shop and buy credits.


      </h2>
      <div class="action-sec2 mt-1">
            <%= link_to "Sign Up Here!",  new_user_registration_path , class: "link-to-txt"%>
       </div>
      <div class="scroll2">
        <img src="<%= asset_path('scroll.svg')%>" alt="" onclick="topFunction2()" id="myArrow2">
      </div>
    </div>

  </div>
</div>

<script type="text/javascript">


myScroll1 = document.getElementById("myArrow1");
window.onscroll = function() {scrollFunction1()};

function scrollFunction1() {
  if (document.body.scrollTop > 10 || document.documentElement.scrollTop > 10) {
    myScroll1.style.display = "block";
  } else {
    myScroll1.style.display = "none";
  }
}
function topFunction1() {
  document.querySelector('.sec2').scrollIntoView({
  behavior: 'smooth'
});
}

// ************************************************ SECOND SCROLL ************************************************//

myScroll2 = document.getElementById("myArrow2");
window.onscroll = function() {scrollFunction2()};

function scrollFunction2() {
  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
    myScroll2.style.display = "block";
  } else {
    myScroll2.style.display = "none";
  }
}
function topFunction2() {
document.querySelector('.card-container-noside').scrollIntoView({
  behavior: 'smooth'
});
  // document.body.scrollTop = 1600; // For Safari
  // document.documentElement.scrollTop = 1600;
}
</script>

app/views/shared/_businessOffers.html.erb
<div class="bus-container">
  <div class="main-item">
      <%= cl_image_tag business.photo.key, quality: :auto, crop: :scale, class:"cl-img" %>
  </div>

  <div class="bus-content-container">
    <div class="bus-infos">
      <h1><%= business.name %> <small>
        <%= link_to "http://www.instagram.com/#{business.instagram}", target: "_blank", rel: "nofollow", class: "link-to-txt" do %>
          <i class="fab fa-instagram"></i>
        <%end%>
      </small> </h1>
      <p><%= business.description %></p>
      <h1>Location</h1>
      <p> <%= business.address %></p>
    </div>

    <% if user_signed_in? %>
      <% if current_user.owner %>
        <div class="bus-infos mt-2">
          <h1>Offers</h1>
          <p>These are the current available offers</p>
        </div>
      <% else %>
        <div class="bus-infos mt-2">
          <h1>Offers</h1>
          <p>Click an offer to add it to your cart </p>
        </div>
      <% end %>
    <% else %>
      <div class="bus-infos mt-2">
        <h1>Offers</h1>
        <p>Create an account before adding to your cart</p>
      </div>
    <% end %>

    <div class="bus-infos bus-offers mt-2">

        <% business.business_offers.each do |business_offer| %>
          <%= link_to add_offer_to_bag_path(business, business_offer.id), method: :post  do %>
            <button class="button-secondary-sm offers">
              <span class="strike"><%= humanized_money_with_symbol(business_offer.offer_amount)%>$</span>
               <%=humanized_money_with_symbol(business_offer.price_cents) %>
               <span style="color:#739C88"> (<%= business_offer.discount%>%)</span>
             </button>
          <% end %>
        <%end%>
    </div>

<% if user_signed_in? %>
  <% if !current_user.owner %>
          <div class="offer-action  button-primary mt-1">
            <%= link_to "VIEW CART", show_cart_path , class: "link-to-white"%>
          </div>
          <div class="offer-action  button-transparent mt-1">
            <%= link_to "Back to Shops", businesses_path , class: "link-to-txt"%>
          </div>
  <% else %>
          <div class="offer-action  button-transparent mt-1">
            <%= link_to "Back to Shops", businesses_path , class: "link-to-txt"%>
          </div>
  <% end %>
<%else%>
          <div class="offer-action  button-transparent mt-1">
            <%= link_to "Back to Shops", businesses_path , class: "link-to-txt"%>
          </div>
<%end%>

  </div>
</div>

    <%= render 'shared/flashes' %>

app/views/shared/_businesses.html.erb
<div class="main-container-side">
  <div class="cat-content">
    <% Category.all.each do |category|%>

    <%= link_to businesses_path(category: category.category_name), class: "link-to", method: :get do %>
    <p class="cat-box-sm"><%= category.category_name %></p>
    <%end%>

    <% end %>
  </div>
  <div class="card-container-side">
    <% businesses.each do |business| %>
    <%= link_to business_path(business), class: "link-to-txt" do %>
    <div class="card-container-item">
      <div class="card">
        <%= cl_image_tag business.photo.key, crop: :scale, quality: :auto, class:"cl-img" %>
        <div class="card-infos">
          <div>
            <h2><%= business.name %></h2>
            <p class="green"><%= business.category.category_name %></p>
          </div>
          <p class="card-empl"><u><%= business.employee_no %></u> people work here</p>
          <% if business.business_offers[0] %>
          <div class="discount-bordered">
            <div class="discount-bordered-inside"> <%= business.business_offers[0].discount %>%</div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
  <div class="centerd-btn-layer">
    <%= link_to businesses_path, class: "link-to" do %>
    <div class="button-secondary">View All</div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible animated infinite fade delay-2s" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-logo">
    <p class="footer-headers">TUCHE</p>
    <p style="font-size: 14px; color: #333333; margin-bottom: 0;">Carefully created online</p>
  </div>
  <div class="footer-contact d-block">
    <p class="footer-headers">Contact</p>
    <div class="footer-box-lg" style="width: 100%; margin-bottom: 0.4rem">
      <a href="mailto:mahsa.khamisi@gmail.com" class="footer-link-to">Email us</a>
    </div>
    <div class="footer-box-lg" style="width: 100%; margin-bottom: 0.4rem">
      <a href="#" class="footer-link-to">Work with us</a>
    </div>
  </div>
  <div class="footer-newsletter">
    <p class="footer-headers">Newsletter</p>
    <p>Click here <a href="/" class="footer-subscribe">to subscribe</a></p>
  </div>
  <div class="footer-social-links">
    <p class="footer-headers">Find Us</p>
    <div class="footer-social-item" style="margin-bottom: 0.4rem"><a href="https://www.facebook.com/" target="_blank">Facebook  <i class="fab fa-facebook"></i></a></div>
    <div class="footer-social-item" style="margin-bottom: 0.4rem"><a href="https://www.instagram.com/panahpanahi" target="_blank">Instagram  <i class="fab fa-instagram"></i></a></div>
    <div class="footer-social-item" ><a href="https://twitter.com/">Twitter  <i class="fab fa-twitter"></i></a></div>
  </div>
</footer>

app/views/shared/_navbar-home.html.erb
<div class="navbar-container">
  <div class="navbar-spc"></div>
  <div class="navbar-box-str">
    <%= link_to businesses_path, class: "link-to-white-solid" do %>
    Stores
    <% end %>
  </div>
  <div class="navbar-box-abt">
    <%= link_to about_path, class: "link-to-white-solid" do %>
      About Us
    <% end %>
  </div>
  <div class="nav-logo">
    <p><a href="/">TUCHE</a></p>
  </div>
  <div class="navbar-box-srch">
    <%= form_tag businesses_path, method: :get do %>
    <%= text_field_tag :query, params[:query], class: "txtfld-ghost-sm", placeholder: "Search" %>
    <% end %>
  </div>
  <%if user_signed_in? %>
  <div class="navbar-box-lg"><%= link_to "logout", destroy_user_session_path, method: :delete, class: "link-to-txt" %>
  </div>
  <%else%>
  <div class="navbar-box-lg dropdown" id="log-action"><img src="<%= asset_path('arrow.svg')%>" alt=""
      class="dropdown-toggle" data-toggle="dropdown">
    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
      <a class="dropdown-item look-style" href="/users/sign_in">Sign in</a>
      <a class="dropdown-item look-style" href="/users/sign_up">Register</a>
    </div>
  </div>
  <%end%>
  <%if user_signed_in?%>
  <div class="navbar-box-bag">
    <%= link_to show_cart_path, class: "link-to-txt" do %>
    <img src="<%= asset_path('bag.svg')%>" alt="">
    <%= current_user.orders.last.order_items.count if current_user.orders && !current_user.orders.last.nil? && !current_user.orders.last.paid %>
    <% end %>
  </div>
  <div class="navbar-box-profile">
    <%= link_to  edit_user_registration_path, class: "link-to-txt" do %>
    <img src="<%= asset_path('profile.svg')%>" alt="">
    <% end %>
  </div>
  <%else%>
  <div class="navbar-box-bag">
    <%= link_to  show_cart_path, class: "link-to-txt" do %>
    <img src="<%= asset_path('bag.svg')%>" alt="" id="profile">
    <% end %>
  </div>
  <div class="navbar-box-profile">
    <%= link_to  "#", class: "link-to-txt" do %>
    <img src="<%= asset_path('profile.svg')%>" alt="">
    <% end %>
    <%flash[:alert] = "You are not logged in"%>
  </div>
  <%end%>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">

  <div class="action">

    <div class="shop action-item">
      Shop
    </div>

    <div class="cart action-item">
      Cart
    </div>
  </div>

  <div class="logo">
    <%= link_to root_path do %>
      <%= image_tag ('tuche2.jpg'), class: "logo_two" %>
    <% end %>
  </div>


  <div class="action-two">

    <%= form_tag businesses_path, method: :get, class: "bg-light" do %>
         <%= text_field_tag :query, params[:query], class: "form-control mr-sm-2 border-0", placeholder: "enter a keyword" %>
    <% end %>

    <div class="login action-item-two">
      <%= link_to "Login", new_user_registration_path %>
    </div>
  </div>

</div>

app/views/shared/_profilePageSkeleton.html.erb
    <%if orderView %>
      <div class="srch-bar">
        <%= form_tag orders_path, method: :get do %>
          <%= text_field_tag :order_query,
            params[:order_query],
            class: "txtfld-ghost mt-2",
            placeholder: "Find an order"
          %>
          <%= button_tag :submit, class: "button-secondary-xs ml-2" do %>
            <img src="<%= asset_path('search.svg') %>" alt="">
          <%end%>
        <% end %>
      </div>
    <%end%>

    <%if !orderView%>
    <div class="srch-bar"></div>
    <%end%>

    <div class="page-container">
      <div class="sidebar">
        <div class="item-box-up">
          <div class="up-spc">
            <%= link_to "Your Profile", edit_user_registration_path, class: "link-to-txt" %>
          </div>
          <div class="up-spc">
            <%= link_to "Transactions History", orders_path, class: "link-to-txt" %>
          </div>
        <% if !current_user.owner%>
          <div class="up-spc">
            <%= link_to "Supported Businesses", businesses_helped_path, class: "link-to-txt" %>
          </div>
        <%end%>
        </div>
    <%if orderView %>
      <%if current_user.owner %>
        <div class="item-box-down">
          <div class="down-ttl">Offer Package:</div>
          <% current_user.businesses[0].business_offers.each do |business_offer|%>
            <div class="down-spc stl">
            <%= link_to orders_path(offer: business_offer.id), class: "link-to-txt", method: :get do %>
              <%=humanized_money_with_symbol(business_offer.offer_amount)%>$ Credit
            <%end%>
          </div>
          <%end%>
        </div>
      <%end%>
    <%end%>
      </div>
    <%if orderView %>
      <div class="page-body-table">
        <div class="order-row">
          <div class="order-cell" style=" font-weight: bold;width: 110px !important;">ORDER NUMBER</div>
          <div class="order-cell" style="font-weight: bold; width: 110px !important;">ORDER DATE</div>
          <div class="order-cell" style="font-weight: bold; width: 110px !important;">EXPIRY DATE</div>
          <div class="order-cell" style="font-weight: bold; width: 90px !important;">TOTAL</div>
          <div class="order-cell" style="font-weight: bold; width: 150px !important;">PAYMENT STATUS</div>
          <div class="order-cell" style="font-weight: bold; width: 150px !important;">CONFIRMATION NO.</div>
          <div class="order-cell" style="font-weight: bold; width: 120px !important;">PACK QUANTITY</div>
          <div class="order-cell" style="font-weight: bold;">GIFT</div>
        </div>

            <% orders.each do |order|%>
            <div class="order-row">
              <div class="order-cell" style="width: 110px !important; color:#333333;"><%= order.id %></div>
              <div class="order-cell" style=" width: 110px !important; color:#333333;"><%= order.order_date %></div>
              <div class="order-cell" style=" width: 110px !important; color:#333333;"><%= order.exp_date %></div>
              <div class="order-cell" style=" width: 90px !important; color:#333333;"><%= order.total_amount_cents %></div>
              <div class="order-cell" style=" width: 150px !important; color:#333333;"><%= order.state %></div>
              <div class="order-cell" style=" width: 150px !important; color:#333333;"><%= order.confirmation_no %></div>
              <div class="order-cell" style=" width: 120px !important; color:#333333;"><%= order.order_items.count %> </div>
              <div class="order-cell" style="width: 110px !important; color:#333333;"><% if order.gift %> <i class="fas fa-gift" data-toggle="modal" data-target="#exampleModal"></i> <%end%>
              </div>
            </div>
            <%end%>
      </div>
    <%end%>
        <%if card %>
      <div class="page-body-card">
<%quantity=0%>
<% empl = 0%>
<%orders = Order.where(user_id: current_user)%>
  <%if !orders.nil?%>
  <%orders.each do |order|%>
    <% order_items = order.order_items %>
    <%order_items.each do |order_item|%>
      <% quantity = quantity + order_item.quantity.to_i %>
      <% empl = empl + order_item.business_offer.business.employee_no.to_i %>
    <%end%>
  <%end%>
  <div class="msg-box">
      <h3>Thank You!</h3>
      <p>You have bought <strong><u> <%= quantity %> </u></strong> credits.
      You have helped <strong><u> <%= empl %> </u></strong>employees!</p>
  </div>
<%end%>




        <div class="main-container-side-t">
          <div class="card-container-side-t">
          <% businesses.each do |business| %>
          <%= link_to business_path(business), class: "link-to-txt" do %>
              <div class="card-container-item">
                <div class="card">
                  <%= cl_image_tag business.photo.key, quality: :auto, crop: :scale, class:"cl-img" %>
                  <div class="card-infos">
                    <div>
                      <h2><%= business.name %></h2>
                      <p class="green">Thanks! You helped <%= business.employee_no %> employees who work here!</p>
                    </div>
                    <div class="discount-bordered">
                      <div class="discount-bordered-inside">
                        <img src=<%= asset_path('check.svg')%> >
                      </div>
                      </div>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    <%end%>
    </div>
  </div>

app/views/shared/_showSeveralBusCard.html.erb
<%if !businesses[0].nil? %>
<div class="card-container-noside">
  <div class="heading" id="3"><%= text %></div>
  <% businesses.each do |business| %>
  <%= link_to business_path(business), class: "link-to-txt" do %>
      <div class="card-container-item">
        <div class="card">
          <%= cl_image_tag business.photo.key, crop: :scale, quality: :auto, class:"cl-img" %>
          <div class="card-infos">
            <div>
              <h2><%= business.name %></h2>
              <p class="green"><%= business.category.category_name %></p>
            </div>
            <p class="card-empl"><u><%= business.employee_no %></u> people work here</p>
            <div class="discount-bordered">
              <% if business.business_offers[0] %>
                <div class="discount-bordered-inside"> <%= business.business_offers[0].discount %>%</div>
              <% end %>
              </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<div class="centerd-btn-layer mt-4 mb-4">
  <%= link_to businesses_path, class: "link-to" do %>
  <div class="button-primary">View All</div>
  <% end %>
</div>
<%end%>