config/routes.rb
Rails.application.routes.draw do

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  devise_for :users
  root to: 'pages#home'

  # # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html




  # devise_for :users, path: 'users', controllers: {
  #   sessions: "users/sessions"
  # }
  get "/businesses/helped", to: "businesses#order_history_businesses", as: "businesses_helped"
  get "/about", to: "pages#about", as: "about"

  resources :businesses, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :business_offers, shallow: true
  end

  resources :orders, only: [:index, :new, :create, :edit, :update, :destroy] do
    resources :order_items, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :payments, only: [:new]
  end



  post "/businesses/:business_id/business_offers/:id/add", to: "business_offers#add_to_bag", as: "add_offer_to_bag"
  post "/businesses/:business_id/business_offers/:id/remove", to: "business_offers#remove_from_bag", as: "remove_from_bag"
  post "/businesses/:business_id/business_offers/:id/increase", to: "business_offers#increase_to_bag", as: "increase_offer_to_bag"
  get "/orders/:business_id/increase", to: "orders#update_total_amount_cents", as: "update_total_amount_cents"
  get "/orders/:business_id/decrease", to: "orders#update_total_amount_cents_checkout", as: "update_total_amount_cents_checkout"
  get "/orders/cart", to: "orders#show_cart", as: "show_cart"



  # get "/businesses/:user_id/withdraw", to: "businesses#withdraw", as: "withdraw"
  # get "/orders/:user_id/transactions", to: "orders#view_history", as: "view_user_history"
  # get "/orders/:user_id/view_all", to: "orders#view_all", as: "view_user_orders"


end

app/models/order.rb
class Order < ApplicationRecord
  # belongs_to :order_item
  has_many :order_items, dependent: :destroy
  has_many :business_offers, through: :order_items
  belongs_to :user
  monetize :total_amount_cents
  before_save :set_expiration_date

  def add_item_quantity(business_offer_id)
      @order_item = OrderItem.where("order_id = ? AND business_offer_id = ?", self.id, business_offer_id.to_i).first

      if !@order_item.nil?
        @order_item.quantity += 1
        @order_item.save
      else
        @order_item =  OrderItem.new(business_offer_id: business_offer_id,
          quantity: 1,
          order_id: self.id)
        @order_item.save
      end

      @order_item
  end

  def decrease_item_quantity(business_offer_id)
      @order_item = OrderItem.where("order_id = ? AND business_offer_id = ?", self.id, business_offer_id.to_i).first
      if !@order_item.nil?
        if @order_item.quantity == 0
          @order_item.quantity = 0
        else
          @order_item.quantity -= 1
        end
        @order_item.save
      end
      @order_item
  end


  # def total_calculator
  #   @order_items = self.order_items
  #   updated_total_amount_cents = 0
  #   # raise
  #   @order_items.each do |order_item|
  #     business_offer = BusinessOffer.find(order_item.business_offer_id)
  #     # This needs to be total of dicscounted amount:
  #     updated_total_amount_cents += business_offer.price_cents * order_item.quantity
  #   end
  #   first_name = User.find(self.user_id).first_name
  #   last_name = User.find(self.user_id).last_name
  #   if total_amount_cents == 0
  #         self.update( total_amount_cents: updated_total_amount_cents, order_date: Date.new)
  #   else
  #   session = Stripe::Checkout::Session.create(
  #     payment_method_types: ['card'],
  #     line_items: [{
  #       name: "#{first_name}, #{last_name}",
  #       amount: self.total_amount_cents,
  #       currency: 'eur',
  #       quantity: 1
  #     }],
  #     success_url: "/orders?payment=success",
  #     cancel_url: "/orders?payment=fail"
  #   )
  #   self.update(checkout_session_id: session.id, total_amount_cents: updated_total_amount_cents, order_date: Date.new)
  # end
  # end

private

  def set_expiration_date
    puts self
    self.exp_date = Date.today + 10
    puts self
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:total_calculator, :update_total_amount_cents, :update_total_amount_cents_checkout, :update]
  before_action :total_calculator, only: [:update_total_amount_cents, :update_total_amount_cents_checkout]

def index
    @orders_index_pundit = policy_scope(Order)
    if params[:payment] == "success"
    current_user.orders.last.update(order_date: Date.today, exp_date: Date.today + 30, state: 'pending', paid: true, owner_paid: true)
    elsif params[:payment] == "fail"
    current_user.orders.last.update(order_date: Date.today, state: 'failed', paid: false, owner_paid: false)
    end
    if current_user.owner
      @orders = []
      business = current_user.businesses.last
      @order_items = business.order_items
      if params[:offer].present?
        # GET BUSINESS ORDERS WHEN THERES A FILTER
        order_items = @order_items.where(business_offer: BusinessOffer.find(params[:offer].to_i))
        @orders = order_items.map { |order_item| order_item.order }.uniq
      elsif params[:order_query].present?
        @order_items.each do |order_item|
          sql_query = "confirmation_no ILIKE :order_query OR CAST(total_amount_cents AS TEXT) ILIKE :order_query OR CAST(order_date AS TEXT) ILIKE :order_query OR CAST(exp_date AS TEXT) ILIKE :order_query AND state = 'pending' AND id = #{order_item.order_id} AND paid = true"
          all_orders = @orders_index_pundit.where(sql_query, order_query: "%#{params[:order_query]}%")
          sql_query = "confirmation_no ILIKE :order_query OR CAST(total_amount_cents AS TEXT) ILIKE :order_query OR CAST(order_date AS TEXT) ILIKE :order_query OR CAST(exp_date AS TEXT) ILIKE :order_query AND  state = 'paid' AND id = #{order_item.order_id} AND paid = true"
          all_orders = @orders_index_pundit.where(sql_query, order_query: "%#{params[:order_query]}%")
          all_orders.each do |order|
            @orders.push(order)
          end
        end
      else
        # GET BUSINESS ORDERS
        @orders = @order_items.map { |order_item| order_item.order }.uniq
      end
      return
    else
      # @orders = Order.where("user_id = ?", current_user.id)
      if params[:order_query].present?
        sql_query = "confirmation_no ILIKE :order_query OR CAST(total_amount_cents AS TEXT)  ILIKE :order_query OR CAST(exp_date AS TEXT) ILIKE :order_query OR CAST(order_date AS TEXT) ILIKE :order_query AND state = 'pending' AND user_id = #{current_user.id} AND paid = true"
        @orders = @orders_index_pundit.where(sql_query, order_query: "%#{params[:order_query]}%")
        sql_query = "confirmation_no ILIKE :order_query OR CAST(total_amount_cents AS TEXT)  ILIKE :order_query OR CAST(exp_date AS TEXT) ILIKE :order_query OR CAST(order_date AS TEXT) ILIKE :order_query AND state = 'paid' AND user_id = #{current_user.id} AND paid = true"
        @orders = @orders_index_pundit.where(sql_query, order_query: "%#{params[:order_query]}%")
        # raise
      else
        @orders = @orders_index_pundit.where("user_id = ?", current_user.id)
      end
    end
  end

  def new
    @order = Order.new
    authorize @order
  end

  def create
    authorize @order
  end


  def show_cart
# If user has no order at all, send false to show empty bag
    if current_user.orders.last.nil?
      @order = false
    else
      @order = current_user.orders.last
        @orders = current_user.orders
        show_alert = @orders.any? do |ord|
          (Date.today + 10) > ord.exp_date if ord.exp_date
        end
        if show_alert
          flash[:alert] = "One or more orders are going to expire within 10 days"
        end
# If user's order is already paid, send false to show empty bag
        if @order.paid
          @order = false
        end
        @order
    end
    authorize Order.new
  end


  def edit
  end


  def update
    authorize @order
    @order.update(gift: true)
    @order.update(order_params)
    render :show_cart
  end


  def destroy; end

  def update_total_amount_cents
    authorize @order
    # @order.total_calculator
    redirect_to business_path(params[:business_id]), notice: "Your order is added to the bag"
  end

  def update_total_amount_cents_checkout
    authorize @order
    # @order.total_calculator
    redirect_to show_cart_path, notice: "Shopping bag is updated!"
  end

  def total_calculator
    @order_items = OrderItem.where("order_id = ?", @order.id)
    updated_total_amount_cents = 0
    @order_items.each do |order_item|
      business_offer = BusinessOffer.find(order_item.business_offer_id)
      # This needs to be total of dicscounted amount:
      updated_total_amount_cents += business_offer.price_cents * order_item.quantity
    end
    @order.update(total_amount_cents: updated_total_amount_cents , order_date: Date.today)

    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        name: "#{current_user.first_name} #{current_user.last_name}",
        amount: updated_total_amount_cents * 100,
        currency: 'eur',
        quantity: 1
      }],
      success_url:"#{orders_url}?payment=success",
      cancel_url: "#{orders_url}?payment=fail"
    )

    @order.update(checkout_session_id: session.id)
  end

  def order_params
    params.require(:order).permit(:gift, :gift_email, :gift_message)
  end
end

app/views/orders/index.html.erb
<%= render 'shared/profilePageSkeleton', orderView: true, card: false, orders: @orders %>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>

app/views/orders/show_cart.html.erb
<%if !@order %>
<div class="shop-bag-container">
  <div class="shop-item-container">
    <div class="shop-ttl">
      <p>SHOPPING BAG ITEMS</p>
    </div>
    <div class="shop-list-container">
        <div class="item-pic"></div>
        <div class="item-descrption">
         <span class="empty-msg"><p>YOUR SHOPPING BAG IS EMPTY!</p></span>
        </div>
        <div class="item-action"></div>
    </div>
  </div>



<!-- ************************************** RIGHT SIDE OF THE PAGE ************************************************* -->

<div class="pay-bag-container">

  <div class="pay-title">
  <p>ORDER SUMMARY</p>
  </div>
  <div class="pay-item1">
    Number of Items: 0
  </div>
  <div class="pay-item2">
    Total Value: -
  </div>

<!-- **************************** CHECK IF TOTAL AMOUNT IS MORE THAN ZERO ******************************* -->
    <div class="pay-btn">
      <button id="pay" class="button-primary-lrg">NO ITEM FOR CHECKOUT</button>
    </div>

    <div class="button-transparent pay-item3">
      <%= link_to "Back to Shops", businesses_path , class: "link-to-txt"%>
    </div>


    <div class="pay-terms">
      <p>
        Our returns are free and easy. If something isn’t quite right, you have 100 days to send it back to us. Read more in our return and refund policy
      </p>
      <p style="color: #94B0B9">
        FREE SHIPPING AND FREE RETURNS ON ALL ORDERS
      </p>
      <p style="color: #94B0B9">
        Because of the current situation, we have extended our returns and refunds policy to 100 days.
      </p>
      <p>
        Please note, order processing may take longer than usual right now. We’re working as fast as we can to get all orders ready, and we will let you know by email as soon as yours is on its way. Thank you for your patience during this difficult time, and - as always - for shopping with COS.
        In accordance with our Privacy Notice, if you are signed in to your COS account, we will share personal data from your account with Klarna for order checkout and payment purposes.
      </p>
    </div>
  </div>
</div>
<!-- Handle shopping bag -->
<% else %>
<% order_items = @order.order_items.sort_by { |k| k["id"] }%>

<div class="shop-bag-container">
  <div class="shop-item-container">
    <div class="shop-ttl">
      <p>SHOPPING BAG ITEMS</p>
    </div>
          <% order_items.each do |order_item|%>
    <div class="shop-list-container">
        <div class="item-pic">
            <%= cl_image_tag order_item.business_offer.business.photo.key, quality: :auto, height: 150, width: 100, crop: :fill, class:"cl-img" %>
        </div>
        <div class="item-descrption">
         <p><strong style="color: #739C88; font-weight: bold"> <%=  order_item.business_offer.business.name %></strong>
          <br>

          Original credit amount: <span class="strike"><%= humanized_money_with_symbol(order_item.business_offer.offer_amount) %></span>
          , but you pay: <%= humanized_money_with_symbol(order_item.business_offer.price_cents) %>
          <br>
                  Quantity
            <%= link_to remove_from_bag_path(order_item.business_offer.business_id,order_item.business_offer.id), method: :post, remote:true do %>
              <img src="<%= asset_path('minus.svg') %>" alt="">
            <% end %>
            <%= order_item.quantity %>
            <%= link_to increase_offer_to_bag_path(order_item.business_offer.business_id,order_item.business_offer.id), method: :post, remote:true do %>
              <img src="<%= asset_path('plus.svg') %>" alt="">
            <% end %>
            </p>
        </div>
        <div class="item-action">
          <p>
            <%= link_to  order_order_item_path(@order, order_item), method: :delete  do %>
              <img src="<%= asset_path('cross.svg') %>" alt="">
            <% end %>
          </p>

        </div>

    </div>
          <% end %>
  </div>



<!-- ************************************** RIGHT SIDE OF THE PAGE ************************************************* -->
  <% quantity = 0 %>
  <% order_items = @order.order_items %>
    <%order_items.each do |order_item|%>
      <% quantity = quantity + order_item.quantity.to_i %>
  <%end%>

<div class="pay-bag-container">

  <div class="pay-title">
  <p>ORDER SUMMARY</p>
  </div>
  <div class="pay-item1">
    Number of Items: <%= quantity %>
  </div>
  <div class="pay-item2">
    Total Value: <%=  humanized_money_with_symbol(@order.total_amount_cents.to_f ) %>
  </div>
    <% if !@order.gift %>
      <%= simple_form_for(@order) do |order| %>
        <div class="gift-check mt-2" id="gift-item">
          <%= order.check_box :gift, class: "checkbox-g" %> Send as a gift!
        </div>
        <div class="gift-textbox" id="gift-div" style="display: none">
          <%= order.input_field :gift_email, placeholder: 'email address', class: "txtfld-ghost"  %> <br>
          <%= order.input_field :gift_message, placeholder: 'type your message..', class: "txtfarea-ghost"  %>
          <%= order.submit "send as a gift", class: "button-primary-gift " %>
        </div>

      <% end %>
    <% else %>
      <div class="gift-check green mt-2" >
        Your order will be sent as a gift to: <%= @order.gift_email %>

      </div>
    <% end %>
<!-- **************************** CHECK IF TOTAL AMOUNT IS MORE THAN ZERO ******************************* -->
    <div class="pay-btn">
      <button id="pay" class="button-primary-lrg">PROCEED TO CHECKOUT</button>
    </div>
              <script src="https://js.stripe.com/v3/"></script>
                <script>
                  var paymentButton = document.getElementById('pay');
                  paymentButton.addEventListener('click', () => {
                    var stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
                    stripe.redirectToCheckout({
                      sessionId: '<%= @order.checkout_session_id %>'
                    });
                  });
                </script>
    <div class="button-transparent pay-item3">
      <%= link_to "Back to Shops", businesses_path , class: "link-to-txt"%>
    </div>


    <div class="pay-terms">
      <p>
        Our returns are free and easy. If something isn’t quite right, you have 100 days to send it back to us. Read more in our return and refund policy
      </p>
      <p style="color: #94B0B9">
        FREE SHIPPING AND FREE RETURNS ON ALL ORDERS
      </p>
      <p style="color: #94B0B9">
        Because of the current situation, we have extended our returns and refunds policy to 100 days.
      </p>
      <p>
        Please note, order processing may take longer than usual right now. We’re working as fast as we can to get all orders ready, and we will let you know by email as soon as yours is on its way. Thank you for your patience during this difficult time, and - as always - for shopping with COS.
        In accordance with our Privacy Notice, if you are signed in to your COS account, we will share personal data from your account with Klarna for order checkout and payment purposes.
      </p>
    </div>
  </div>
</div>

<%end%>

    <%= render 'shared/flashes' %>

                <script>
var gift = document.getElementById('order_gift');
gift.addEventListener( 'change', function() {
  var x = document.getElementById("gift-div");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
});

                </script>